function opti_mode = mode_test(x)

global model

large_penalty = 1e6;

%% Original parameter settings
model.param('par5').set( ...
    'th1_n',num2str(x(1),17));

model.param('par5').set( ...
    'th2_n',num2str(x(2),17));

model.param('par5').set( ...
    'r1n',num2str(x(3),17));

model.param('par5').set( ...
    'r2n',num2str(x(4),17));

model.param('par5').set( ...
    'z1_n',num2str(x(5),17));

model.param('par5').set( ...
    'z2_n',num2str(x(6),17));

model.param("par7").set( ...
    "dis_c2_x5n",num2str(x(7),17));

model.param("par8").set( ...
    "xy_theta_n",num2str(x(8),17));

model.param("par8").set( ...
    "thx_n",num2str(x(9),17));

try
    %% Eigenfrequency study
    model.study("std1").run();

    %% Basic settings
    unit = 100*1e-3;

    R = 1*unit;
    L = 30*unit;
    cu = 1;

    mic_anglur_num = 4;
    mic_z_num = 1;

    mic_num = ...
        mic_anglur_num*mic_z_num;

    D = 200;
    z = 20;
    z_t = 0/2;

    dset = 'dset1';

    %% Complex eigenfrequencies
    f1 = mphglobal( ...
        model, ...
        'freq', ...
        'dataset',dset);

    f1 = f1(:);

    freq = real(f1);
    freq_imag = abs(imag(f1));

    %% Target frequency interval
    freq_low = 1300;
    freq_high = 1600;

    freq_range = find( ...
        isfinite(freq) & ...
        isfinite(freq_imag) & ...
        freq >= freq_low & ...
        freq <= freq_high);

    if isempty(freq_range)
        opti_mode = large_penalty;
        return
    end

    %% Sampling planes
    z1 = 0.5;
    z2 = -0.5;

    [mg_t1,ph_t1] = comsol_tiqu( ...
        mic_anglur_num, ...
        z1, ...
        mic_z_num, ...
        R, ...
        dset);

    [mg_t2,ph_t2] = comsol_tiqu( ...
        mic_anglur_num, ...
        z2, ...
        mic_z_num, ...
        R, ...
        dset);

    %% Only process modes inside the target interval
    candidate_number = ...
        numel(freq_range);

    out1 = zeros( ...
        candidate_number,3);

    out2 = zeros( ...
        candidate_number,3);

    for k = 1:candidate_number

        index = freq_range(k);

        upper_mode = mode_mn_t_radti( ...
            mg_t1(index,:).', ...
            ph_t1(index,:).', ...
            freq(index), ...
            mic_anglur_num, ...
            mic_num, ...
            mic_z_num, ...
            D,z,z_t);

        lower_mode = mode_mn_tt_radti( ...
            mg_t2(index,:).', ...
            ph_t2(index,:).', ...
            freq(index), ...
            mic_anglur_num, ...
            mic_num, ...
            mic_z_num, ...
            D,z,z_t);

        out1(k,:) = ...
            reshape(upper_mode,1,[]);

        out2(k,:) = ...
            reshape(lower_mode,1,[]);

    end

    %% Six radiation channels
    % Column order: [-1,0,+1]

    Pup_m1 = max( ...
        real(out1(:,1)),0);

    Pup_0 = max( ...
        real(out1(:,2)),0);

    Pup_p1 = max( ...
        real(out1(:,3)),0);

    Pdn_m1 = max( ...
        real(out2(:,1)),0);

    Pdn_0 = max( ...
        real(out2(:,2)),0);

    Pdn_p1 = max( ...
        real(out2(:,3)),0);

    %% Total radiation
    Ptotal = ...
        Pup_m1 + ...
        Pup_0 + ...
        Pup_p1 + ...
        Pdn_m1 + ...
        Pdn_0 + ...
        Pdn_p1;

    %% Leakage outside upward +1
    Pleak = ...
        Pup_m1 + ...
        Pup_0 + ...
        Pdn_m1 + ...
        Pdn_0 + ...
        Pdn_p1;

    %% Remove invalid modes
    maximum_power = max(Ptotal);

    if isempty(maximum_power) || ...
            ~isfinite(maximum_power) || ...
            maximum_power <= 0

        opti_mode = large_penalty;
        return
    end

    power_floor = max( ...
        maximum_power*1e-12, ...
        realmin);

    valid = ...
        isfinite(Ptotal) & ...
        isfinite(Pup_p1) & ...
        Ptotal > power_floor;

    if ~any(valid)
        opti_mode = large_penalty;
        return
    end

    %% Target-channel fraction
    eta_up_p1 = ...
        Pup_p1(valid)./Ptotal(valid);

    eta_up_p1 = min( ...
        max(eta_up_p1,0),1);

    %% Leakage fraction
    leakage_ratio = ...
        Pleak(valid)./Ptotal(valid);

    leakage_ratio = min( ...
        max(leakage_ratio,0),1);

    %% Imaginary-frequency values of valid modes
    candidate_imag = ...
        freq_imag(freq_range);

    candidate_imag = ...
        candidate_imag(valid);

    %% Objective settings
    imag_target = 0.06;

    leakage_tolerance = 0.01;
    imag_tolerance = 0.01;

    %% Radiation error
    radiation_error = ...
        (leakage_ratio/ ...
        leakage_tolerance).^2;

    %% Imaginary-frequency error
    imaginary_error = ...
        ((candidate_imag-imag_target)/ ...
        imag_tolerance).^2;

    %% Combined objective for every mode
    objective_each_mode = ...
        radiation_error + ...
        imaginary_error;

    %% Select the best eigenmode
    opti_mode = ...
        min(objective_each_mode);

    if isempty(opti_mode) || ...
            ~isfinite(opti_mode)

        opti_mode = large_penalty;
    end

catch
    opti_mode = large_penalty;
end

end