function out = opti_comsol(x)
%
% opti_comsol.m
%
% Model exported on Mar 12 2026, 16:00 by COMSOL 6.3.0.290.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');
model.hist.disable;
model.modelPath(['D:\' native2unicode(hex2dec({'97' '5e'}), 'unicode')  native2unicode(hex2dec({'5b' 'f9'}), 'unicode')  native2unicode(hex2dec({'79' 'f0'}), 'unicode')  native2unicode(hex2dec({'8f' '90'}), 'unicode')  native2unicode(hex2dec({'5c' '04'}), 'unicode') ]);

model.label([native2unicode(hex2dec({'53' 'cc'}), 'unicode')  native2unicode(hex2dec({'5c' '42'}), 'unicode')  native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '84'}), 'unicode')  native2unicode(hex2dec({'97' '5e'}), 'unicode')  native2unicode(hex2dec({'5b' 'f9'}), 'unicode')  native2unicode(hex2dec({'79' 'f0'}), 'unicode')  native2unicode(hex2dec({'6d' '4b'}), 'unicode')  native2unicode(hex2dec({'8b' 'd5'}), 'unicode') '_' native2unicode(hex2dec({'4e' 'ff'}), 'unicode')  native2unicode(hex2dec({'71' '67'}), 'unicode') 'optic.mph']);

model.param.set('D', '100[mm]');
model.param.set('L', '300[mm]*2');
model.param.set('delta_th', '10[deg]');
model.param.set('zi', '0.05[m]');
model.param.set('pml', 'L/4');
model.param.set('f0', '3000[Hz]');
model.param.set('c0', '343[m/s]');
model.param.set('lbd', 'c0/f0');
model.param.group.create('par2');
model.param('par2').set('G', 'pi/L');
model.param('par2').set('m', '0');
model.param.group.create('par3');
model.param('par3').set('r1', 'r_min+(r_max-r_min)*r1n', [native2unicode(hex2dec({'59' '16'}), 'unicode')  native2unicode(hex2dec({'57' '08'}), 'unicode') '1' native2unicode(hex2dec({'76' '84'}), 'unicode')  native2unicode(hex2dec({'53' '9a'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ]);
model.param('par3').set('th1', 'th1_min+(th1_max-th1_min)*th1_n', [native2unicode(hex2dec({'59' '16'}), 'unicode')  native2unicode(hex2dec({'57' '08'}), 'unicode') '1' native2unicode(hex2dec({'76' '84'}), 'unicode')  native2unicode(hex2dec({'62' '47'}), 'unicode')  native2unicode(hex2dec({'5f' '62'}), 'unicode')  native2unicode(hex2dec({'89' 'd2'}), 'unicode') ]);
model.param('par3').set('r2', 'r_min+(r_max-r_min)*r2n', [native2unicode(hex2dec({'59' '16'}), 'unicode')  native2unicode(hex2dec({'57' '08'}), 'unicode') '2' native2unicode(hex2dec({'76' '84'}), 'unicode')  native2unicode(hex2dec({'53' '9a'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ]);
model.param('par3').set('th2', 'th1_min+(th1_max-th1_min)*th2_n', [native2unicode(hex2dec({'59' '16'}), 'unicode')  native2unicode(hex2dec({'57' '08'}), 'unicode') '2' native2unicode(hex2dec({'76' '84'}), 'unicode')  native2unicode(hex2dec({'62' '47'}), 'unicode')  native2unicode(hex2dec({'5f' '62'}), 'unicode')  native2unicode(hex2dec({'89' 'd2'}), 'unicode') ]);
model.param('par3').set('z1', 'z_min+(z_max-z_min)*z1_n', [native2unicode(hex2dec({'59' '16'}), 'unicode')  native2unicode(hex2dec({'57' '08'}), 'unicode') '1' native2unicode(hex2dec({'76' '84'}), 'unicode') 'z' native2unicode(hex2dec({'54' '11'}), 'unicode')  native2unicode(hex2dec({'62' 'c9'}), 'unicode')  native2unicode(hex2dec({'4f' '38'}), 'unicode') ]);
model.param('par3').set('z2', 'z_min+(z_max-z_min)*z2_n', [native2unicode(hex2dec({'59' '16'}), 'unicode')  native2unicode(hex2dec({'57' '08'}), 'unicode') '2' native2unicode(hex2dec({'76' '84'}), 'unicode') 'z' native2unicode(hex2dec({'54' '11'}), 'unicode')  native2unicode(hex2dec({'62' 'c9'}), 'unicode')  native2unicode(hex2dec({'4f' '38'}), 'unicode') ]);
model.param.group.create('par4');
model.param('par4').set('th1_max', '180[deg]');
model.param('par4').set('th1_min', '10[deg]');
model.param('par4').set('r_max', 'lbd/4');
model.param('par4').set('r_min', 'lbd/16');
model.param('par4').set('z_min', 'lbd/16');
model.param('par4').set('z_max', 'lbd/2');
model.param.group.create('par5');
model.param('par5').set('th1_n', num2str(x(1)));
model.param('par5').set('th2_n', num2str(x(2)));
model.param('par5').set('r1n', num2str(x(3)));
model.param('par5').set('r2n', num2str(x(4)));
model.param('par5').set('z1_n', num2str(x(5)));
model.param('par5').set('z2_n', num2str(x(6)));
model.param('par5').label([native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '84'}), 'unicode')  native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.result.table.create('evl3', 'Table');

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').geomRep('cadps');
model.component('comp1').geom('geom1').designBooleans(true);
model.component('comp1').geom('geom1').create('cyl1', 'Cylinder');
model.component('comp1').geom('geom1').feature('cyl1').set('r', 'D/2');
model.component('comp1').geom('geom1').feature('cyl1').set('h', 'L+pml*2');
model.component('comp1').geom('geom1').feature('cyl1').set('pos', {'0' '0' '-L/2-pml'});
model.component('comp1').geom('geom1').feature('cyl1').set('layername', {[native2unicode(hex2dec({'5c' '42'}), 'unicode') ' 1']});
model.component('comp1').geom('geom1').feature('cyl1').setIndex('layer', 'L/4', 0);
model.component('comp1').geom('geom1').feature('cyl1').set('layerside', false);
model.component('comp1').geom('geom1').feature('cyl1').set('layerbottom', true);
model.component('comp1').geom('geom1').feature('cyl1').set('layertop', true);
model.component('comp1').geom('geom1').create('wp1', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp1').set('quickz', 'zi');
model.component('comp1').geom('geom1').feature('wp1').set('unite', true);
model.component('comp1').geom('geom1').feature('wp1').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('c1').set('r', 'D/2');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('c1').set('angle', 'th1');
model.component('comp1').geom('geom1').feature('wp1').geom.create('c2', 'Circle');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('c2').set('r', 'r1+D/2');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('c2').set('angle', 'th1');
model.component('comp1').geom('geom1').feature('wp1').geom.create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('dif1').selection('input').set({'c2'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('dif1').selection('input2').set({'c1'});
model.component('comp1').geom('geom1').create('ext1', 'Extrude');
model.component('comp1').geom('geom1').feature('ext1').setIndex('distance', 'z1', 0);
model.component('comp1').geom('geom1').feature('ext1').selection('input').set({'wp1'});
model.component('comp1').geom('geom1').create('wp2', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp2').set('quickz', 'zi+z1/2-z2/2');
model.component('comp1').geom('geom1').feature('wp2').set('unite', true);
model.component('comp1').geom('geom1').feature('wp2').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('c1').set('r', 'r2+D/2');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('c1').set('angle', 'th2');
model.component('comp1').geom('geom1').feature('wp2').geom.create('c2', 'Circle');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('c2').set('r', 'D/2');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('c2').set('angle', 'th2');
model.component('comp1').geom('geom1').feature('wp2').geom.create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('dif1').selection('input').set({'c1'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('dif1').selection('input2').set({'c2'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('rot1', 'Rotate');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('rot1').set('rot', 'th1+delta_th');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('rot1').selection('input').set({'dif1'});
model.component('comp1').geom('geom1').create('ext2', 'Extrude');
model.component('comp1').geom('geom1').feature('ext2').setIndex('distance', 'z2', 0);
model.component('comp1').geom('geom1').feature('ext2').selection('input').set({'wp2'});
model.component('comp1').geom('geom1').create('wp3', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp3').set('quickz', 'zi');
model.component('comp1').geom('geom1').feature('wp3').set('unite', true);
model.component('comp1').geom('geom1').feature('wp3').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('c1').set('r', 'r1+D/2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('c1').set('angle', 'th1');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('c1').set('rot', '+180');
model.component('comp1').geom('geom1').feature('wp3').geom.create('c2', 'Circle');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('c2').set('r', 'D/2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('c2').set('angle', 'th1');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('c2').set('rot', 180);
model.component('comp1').geom('geom1').feature('wp3').geom.create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('dif1').selection('input').set({'c1'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('dif1').selection('input2').set({'c2'});
model.component('comp1').geom('geom1').create('ext3', 'Extrude');
model.component('comp1').geom('geom1').feature('ext3').setIndex('distance', 'z1', 0);
model.component('comp1').geom('geom1').feature('ext3').selection('input').set({'wp3'});
model.component('comp1').geom('geom1').create('wp4', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp4').set('quickz', 'zi+z1/2-z2/2');
model.component('comp1').geom('geom1').feature('wp4').set('unite', true);
model.component('comp1').geom('geom1').feature('wp4').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('c1').set('r', 'r2+D/2');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('c1').set('angle', 'th2');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('c1').set('rot', 180);
model.component('comp1').geom('geom1').feature('wp4').geom.create('c2', 'Circle');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('c2').set('r', 'D/2');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('c2').set('angle', 'th2');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('c2').set('rot', 180);
model.component('comp1').geom('geom1').feature('wp4').geom.create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('dif1').selection('input').set({'c1'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('dif1').selection('input2').set({'c2'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('rot1', 'Rotate');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('rot1').set('rot', 'th1+delta_th');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('rot1').selection('input').set({'dif1'});
model.component('comp1').geom('geom1').create('ext4', 'Extrude');
model.component('comp1').geom('geom1').feature('ext4').setIndex('distance', 'z2', 0);
model.component('comp1').geom('geom1').feature('ext4').selection('input').set({'wp4'});
model.component('comp1').geom('geom1').create('rot1', 'Rotate');
model.component('comp1').geom('geom1').feature('rot1').active(false);
model.component('comp1').geom('geom1').feature('rot1').set('keep', true);
model.component('comp1').geom('geom1').feature('rot1').setIndex('rot', '180', 0);
model.component('comp1').geom('geom1').feature('rot1').selection('input').set({'ext1' 'ext2'});
model.component('comp1').geom('geom1').create('mir1', 'Mirror');
model.component('comp1').geom('geom1').feature('mir1').set('keep', true);
model.component('comp1').geom('geom1').feature('mir1').selection('input').set({'ext1' 'ext2' 'ext3' 'ext4'});
model.component('comp1').geom('geom1').create('rot2', 'Rotate');
model.component('comp1').geom('geom1').feature('rot2').active(false);
model.component('comp1').geom('geom1').feature('rot2').setIndex('rot', '10', 0);
model.component('comp1').geom('geom1').feature('rot2').selection('input').set({'mir1(2)' 'mir1(4)'});
model.component('comp1').geom('geom1').create('rot3', 'Rotate');
model.component('comp1').geom('geom1').feature('rot3').setIndex('rot', '10', 0);
model.component('comp1').geom('geom1').feature('rot3').selection('input').set({'ext1' 'ext2' 'ext3' 'ext4'});
model.component('comp1').geom('geom1').nodeGroup.create('grp1');
model.component('comp1').geom('geom1').nodeGroup('grp1').placeAfter('cyl1');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('wp1');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('ext1');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('wp2');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('ext2');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('wp3');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('ext3');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('wp4');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('ext4');
model.component('comp1').geom('geom1').nodeGroup('grp1').add('rot1');
model.component('comp1').geom('geom1').run;
model.component('comp1').geom('geom1').run('fin');

model.component('comp1').variable.create('var1');
model.component('comp1').variable('var1').set('th', 'atan2(y,x)');
model.component('comp1').variable('var1').set('r', 'sqrt(x^2+y^2)');
model.component('comp1').variable('var1').set('p10', 'besselj(1,k10*r)*exp(-1i*1*th)*exp(-1i*kz*z)');
model.component('comp1').variable('var1').set('k10', '1.8412/(D/2)');
model.component('comp1').variable('var1').set('kz', 'sqrt(k0^2-k10^2)');
model.component('comp1').variable('var1').set('k0', 'acpr.k');

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material('mat1').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('rho', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('k', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('cs', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an1', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an2', 'Analytic');
model.component('comp1').material('mat1').propertyGroup.create('RefractiveIndex', 'RefractiveIndex', 'Refractive index');
model.component('comp1').material('mat1').propertyGroup.create('NonlinearModel', 'NonlinearModel', 'Nonlinear model');
model.component('comp1').material('mat1').propertyGroup.create('idealGas', 'idealGas', 'Ideal gas');
model.component('comp1').material('mat1').propertyGroup('idealGas').func.create('Cp', 'Piecewise');

model.component('comp1').coordSystem.create('pml1', 'PML');
model.component('comp1').coordSystem('pml1').selection.set([6 8]);

model.component('comp1').physics.create('acpr', 'PressureAcoustics', 'geom1');
model.component('comp1').physics('acpr').create('pc1', 'PeriodicCondition', 2);
model.component('comp1').physics('acpr').feature('pc1').selection.set([23 31]);
model.component('comp1').physics('acpr').create('bpf1', 'BackgroundPressureField', 3);
model.component('comp1').physics('acpr').feature('bpf1').selection.set([7]);

model.component('comp1').mesh('mesh1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').create('size2', 'Size');
model.component('comp1').mesh('mesh1').create('se1', 'SizeExpression');
model.component('comp1').mesh('mesh1').create('dis1', 'Distribution');
model.component('comp1').mesh('mesh1').create('ftet1', 'FreeTet');
model.component('comp1').mesh('mesh1').create('swe1', 'Sweep');
model.component('comp1').mesh('mesh1').feature('size1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('size1').selection.set([1 2 3 4 5 7 9 10 11]);
model.component('comp1').mesh('mesh1').feature('size2').selection.geom('geom1', 2);
model.component('comp1').mesh('mesh1').feature('size2').selection.set([1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68]);
model.component('comp1').mesh('mesh1').feature('se1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('se1').selection.set([1 2 3 4 5 7 9 10 11]);
model.component('comp1').mesh('mesh1').feature('dis1').selection.geom('geom1', 1);
model.component('comp1').mesh('mesh1').feature('dis1').selection.set([26 36 69 81 84 96 131 137]);
model.component('comp1').mesh('mesh1').feature('ftet1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('ftet1').selection.set([1 2 3 4 5 7 9 10 11]);
model.component('comp1').mesh('mesh1').feature('swe1').selection.geom('geom1', 3);
model.component('comp1').mesh('mesh1').feature('swe1').selection.set([6 8]);
model.component('comp1').mesh('mesh1').feature('swe1').create('dis1', 'Distribution');

model.result.table('evl3').label('Evaluation 3D');
model.result.table('evl3').comments([native2unicode(hex2dec({'4e' 'a4'}), 'unicode')  native2unicode(hex2dec({'4e' '92'}), 'unicode')  native2unicode(hex2dec({'76' '84'}), 'unicode')  native2unicode(hex2dec({'4e' '09'}), 'unicode')  native2unicode(hex2dec({'7e' 'f4'}), 'unicode')  native2unicode(hex2dec({'50' '3c'}), 'unicode') ]);

model.component('comp1').view('view2').axis.set('xmin', -0.2752538025379181);
model.component('comp1').view('view2').axis.set('xmax', 0.30325379967689514);
model.component('comp1').view('view2').axis.set('ymin', -0.17115919291973114);
model.component('comp1').view('view2').axis.set('ymax', 0.199111670255661);
model.component('comp1').view('view3').axis.set('xmin', -0.18593549728393555);
model.component('comp1').view('view3').axis.set('xmax', 0.23281165957450867);
model.component('comp1').view('view3').axis.set('ymin', -0.11056837439537048);
model.component('comp1').view('view3').axis.set('ymax', 0.15791967511177063);
model.component('comp1').view('view4').axis.set('xmin', -0.1381862759590149);
model.component('comp1').view('view4').axis.set('xmax', 0.1383642852306366);
model.component('comp1').view('view4').axis.set('ymin', -0.06820454448461533);
model.component('comp1').view('view4').axis.set('ymax', 0.08482344448566437);
model.component('comp1').view('view5').axis.set('xmin', -0.12033744156360626);
model.component('comp1').view('view5').axis.set('xmax', 0.13319844007492065);
model.component('comp1').view('view5').axis.set('ymin', -0.05607590079307556);
model.component('comp1').view('view5').axis.set('ymax', 0.08421700447797775);

model.component('comp1').material('mat1').label('Air');
model.component('comp1').material('mat1').set('family', 'air');
model.component('comp1').material('mat1').propertyGroup('def').label('Basic');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').label('Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('pieces', {'200.0' '1600.0' '-8.38278E-7+8.35717342E-8*T^1-7.69429583E-11*T^2+4.6437266E-14*T^3-1.06585607E-17*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').label('Piecewise 2');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').label('Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('expr', 'pA*0.02897/R_const[K*mol/J]/T');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('args', {'pA' 'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('argunit', {'Pa' 'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('plotaxis', {'off' 'on'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('plotfixedvalue', {'101325' '273.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '293.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('k').label('Piecewise 3');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('pieces', {'200.0' '1600.0' '-0.00227583562+1.15480022E-4*T^1-7.90252856E-8*T^2+4.11702505E-11*T^3-7.43864331E-15*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').label('Analytic 2');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('expr', 'sqrt(1.4*R_const[K*mol/J]/0.02897*T)');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('plotfixedvalue', {'273.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').label('Analytic 1');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('expr', '-1/rho(pA,T)*d(rho(pA,T),T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('args', {'pA' 'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('fununit', '1/K');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('argunit', {'Pa' 'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('plotaxis', {'off' 'on'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('plotfixedvalue', {'101325' '273.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').label('Analytic 2a');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('funcname', 'muB');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('expr', '0.6*eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('plotfixedvalue', {'200'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('plotargs', {'T' '200' '1600'});
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.component('comp1').material('mat1').propertyGroup('def').set('molarmass', '');
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', '');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('molarmass', '0.02897[kg/mol]');
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.component('comp1').material('mat1').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho(pA,T)');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('soundspeed', 'cs(T)');
model.component('comp1').material('mat1').propertyGroup('def').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup('def').addInput('pressure');
model.component('comp1').material('mat1').propertyGroup('RefractiveIndex').label('Refractive index');
model.component('comp1').material('mat1').propertyGroup('RefractiveIndex').set('n', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('NonlinearModel').label('Nonlinear model');
model.component('comp1').material('mat1').propertyGroup('NonlinearModel').set('BA', 'def.gamma-1');
model.component('comp1').material('mat1').propertyGroup('idealGas').label('Ideal gas');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').label('Piecewise 2');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('Rs', 'R_const/Mn');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('heatcapacity', 'Cp(T)');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('ratioofspecificheat', '1.4');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('molarmass', '0.02897[kg/mol]');
model.component('comp1').material('mat1').propertyGroup('idealGas').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup('idealGas').addInput('pressure');
model.component('comp1').material('mat1').materialType('nonSolid');

model.component('comp1').coordSystem('pml1').set('PMLfactor', '3');

model.component('comp1').physics('acpr').prop('MeshControl').set('SizeControlParameter', 'Frequency');
model.component('comp1').physics('acpr').prop('MeshControl').set('PhysicsControlledMeshMaximumFrequency', '3000[Hz]');
model.component('comp1').physics('acpr').feature('pc1').set('PeriodicType', 'Floquet');
model.component('comp1').physics('acpr').feature('pc1').set('kFloquet', {'0'; '0'; 'm*G'});
model.component('comp1').physics('acpr').feature('pc1').active(false);
model.component('comp1').physics('acpr').feature('bpf1').set('p', 'p10');
model.component('comp1').physics('acpr').feature('bpf1').set('PressureFieldType', 'UserDefined');
model.component('comp1').physics('acpr').feature('bpf1').active(false);

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 3);
model.component('comp1').mesh('mesh1').feature('size').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size').set('hmax', '0.036920');
model.component('comp1').mesh('mesh1').feature('size').set('hmin', '0.0022430');
model.component('comp1').mesh('mesh1').feature('size1').set('hauto', 3);
model.component('comp1').mesh('mesh1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size1').set('hmax', '0.036920');
model.component('comp1').mesh('mesh1').feature('size1').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('size1').set('hmin', '9.0000E-6');
model.component('comp1').mesh('mesh1').feature('size1').set('hminactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hauto', 3);
model.component('comp1').mesh('mesh1').feature('size2').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('size2').set('hmax', '0.011530');
model.component('comp1').mesh('mesh1').feature('size2').set('hmaxactive', true);
model.component('comp1').mesh('mesh1').feature('size2').set('hmin', '3.4590E-4');
model.component('comp1').mesh('mesh1').feature('size2').set('hminactive', true);

model.sol.create('sol1');

model.component('comp1').mesh('mesh1').feature('se1').set('evaltype', 'initialexpression');
model.component('comp1').mesh('mesh1').feature('se1').set('sizeexpr', 'subst(real(acpr.c_c),acpr.freq,acpr.freqmax)/acpr.freqmax/5');
model.component('comp1').mesh('mesh1').feature('dis1').set('type', 'predefined');
model.component('comp1').mesh('mesh1').feature('dis1').set('elemcount', 8);
model.component('comp1').mesh('mesh1').feature('swe1').feature('dis1').set('numelem', 8);

model.study.create('std1');
model.study('std1').create('eig', 'Eigenfrequency');

model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('e1', 'Eigenvalue');
model.sol('sol1').feature('e1').create('d1', 'Direct');
model.sol('sol1').feature('e1').create('i1', 'Iterative');
model.sol('sol1').feature('e1').create('i2', 'Iterative');
model.sol('sol1').feature('e1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('e1').feature('i2').create('mg1', 'Multigrid');

model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').create('surf1', 'Surface');

model.study('std1').feature('eig').set('neigs', 30);
model.study('std1').feature('eig').set('neigsactive', true);
model.study('std1').feature('eig').set('eigunit', 'kHz');
model.study('std1').feature('eig').set('shift', '3');
model.study('std1').feature('eig').set('ftplistmethod', 'manual');

model.sol('sol1').feature('st1').label([native2unicode(hex2dec({'7f' '16'}), 'unicode')  native2unicode(hex2dec({'8b' 'd1'}), 'unicode')  native2unicode(hex2dec({'65' 'b9'}), 'unicode')  native2unicode(hex2dec({'7a' '0b'}), 'unicode') ': ' native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ]);
model.sol('sol1').feature('v1').label([native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('e1').label([native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'50' '3c'}), 'unicode')  native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('e1').set('neigs', 30);
model.sol('sol1').feature('e1').set('eigunit', 'kHz');
model.sol('sol1').feature('e1').set('shift', '3');
model.sol('sol1').feature('e1').set('eigref', '100');
model.sol('sol1').feature('e1').set('filtereigexpression', {'real(freq)+1e-6>0'});
model.sol('sol1').feature('e1').set('filtereigdescription', {[native2unicode(hex2dec({'96' '3b'}), 'unicode')  native2unicode(hex2dec({'5c' '3c'}), 'unicode')  native2unicode(hex2dec({'56' 'fa'}), 'unicode')  native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ]});
model.sol('sol1').feature('e1').feature('dDef').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode') ' 2']);
model.sol('sol1').feature('e1').feature('aDef').label([native2unicode(hex2dec({'9a' 'd8'}), 'unicode')  native2unicode(hex2dec({'7e' 'a7'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('e1').feature('aDef').set('complexfun', true);
model.sol('sol1').feature('e1').feature('d1').active(true);
model.sol('sol1').feature('e1').feature('d1').label('Suggested Direct Solver (acpr)');
model.sol('sol1').feature('e1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('e1').feature('i1').label('Suggested Iterative Solver (GMRES with GMG) (acpr)');
model.sol('sol1').feature('e1').feature('i1').feature('ilDef').label([native2unicode(hex2dec({'4e' '0d'}), 'unicode')  native2unicode(hex2dec({'5b' '8c'}), 'unicode')  native2unicode(hex2dec({'51' '68'}), 'unicode') ' LU ' native2unicode(hex2dec({'52' '06'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i1').feature('mg1').label([native2unicode(hex2dec({'59' '1a'}), 'unicode')  native2unicode(hex2dec({'91' 'cd'}), 'unicode')  native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('e1').feature('i1').feature('mg1').feature('pr').label([native2unicode(hex2dec({'98' '84'}), 'unicode')  native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'6e' 'd1'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('e1').feature('i1').feature('mg1').feature('po').label([native2unicode(hex2dec({'54' '0e'}), 'unicode')  native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'6e' 'd1'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('e1').feature('i1').feature('mg1').feature('cs').label([native2unicode(hex2dec({'7c' '97'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i1').feature('mg1').feature('cs').feature('dDef').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i2').label('Suggested Iterative Solver (FGMRES with GMG) (acpr)');
model.sol('sol1').feature('e1').feature('i2').set('linsolver', 'fgmres');
model.sol('sol1').feature('e1').feature('i2').feature('ilDef').label([native2unicode(hex2dec({'4e' '0d'}), 'unicode')  native2unicode(hex2dec({'5b' '8c'}), 'unicode')  native2unicode(hex2dec({'51' '68'}), 'unicode') ' LU ' native2unicode(hex2dec({'52' '06'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i2').feature('mg1').label([native2unicode(hex2dec({'59' '1a'}), 'unicode')  native2unicode(hex2dec({'91' 'cd'}), 'unicode')  native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('e1').feature('i2').feature('mg1').feature('pr').label([native2unicode(hex2dec({'98' '84'}), 'unicode')  native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'6e' 'd1'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i2').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('e1').feature('i2').feature('mg1').feature('po').label([native2unicode(hex2dec({'54' '0e'}), 'unicode')  native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'6e' 'd1'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i2').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('e1').feature('i2').feature('mg1').feature('cs').label([native2unicode(hex2dec({'7c' '97'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('e1').feature('i2').feature('mg1').feature('cs').feature('dDef').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode') ' 1']);

model.study('std1').runNoGen;

model.result('pg1').set('looplevel', [10]);
model.result('pg1').feature('surf1').set('resolution', 'normal');

out = model;
