function [T,S]=compare_tvb_loss_mac(varargin)
%COMPARE_TVB_LOSS_MAC Compare COMSOL and MATLAB TVB shifts by mode tracking.

here=fileparts(mfilename('fullpath'));
ip=inputParser;
ip.addParameter('NoLossComparisonFile',fullfile(here,'output_no_loss_pml_pass', ...
    'all_comsol_eigenfrequency_forward_backward.csv'));
ip.addParameter('ComsolTrackingFile',fullfile(here,'comsol_tvb_mac_mapping.csv'));
ip.addParameter('MatlabNoLossFile',fullfile(here,'matlab_p1_pml_noloss_mac.mat'));
ip.addParameter('MatlabLossFile',fullfile(here,'matlab_p1_pml_tvb_mac.mat'));
ip.addParameter('OutputDir',fullfile(here,'output_tvb_mac_comparison'));
ip.addParameter('MeaningfulLossFloorHz',1.0);
ip.parse(varargin{:});opt=ip.Results;

C=readtable(opt.NoLossComparisonFile,'VariableNamingRule','preserve');
CT=readtable(opt.ComsolTrackingFile,'VariableNamingRule','preserve');
A=load(opt.MatlabNoLossFile,'S0');B=load(opt.MatlabLossFile,'SL');
S0=A.S0;SL=B.SL;

P=S0.modeSamples.';Q=SL.modeSamples.';
P=P./max(vecnorm(P,2,2),eps);Q=Q./max(vecnorm(Q,2,2),eps);
MAC=abs(P*Q').^2;
rel=abs(real(S0.frequency(:))-real(SL.frequency(:).'))./ ...
    max(abs(real(S0.frequency(:))),eps);
cost=1-MAC+0.05*rel/0.15;cost(rel>0.15)=1e4+rel(rel>0.15);
if exist('matchpairs','file')~=2,error('Statistics Toolbox matchpairs is required.');end
pairs=sortrows(matchpairs(cost,1e6,'min'),1);
lossForNoLoss=nan(numel(S0.frequency),1);lossForNoLoss(pairs(:,1))=pairs(:,2);

n=height(C);m0=zeros(n,1);
for k=1:n
    target=complex(C.theory_real_Hz(k),C.theory_imag_Hz(k));
    scale=max(abs(target),1);
    [d,m0(k)]=min(abs(S0.frequency-target)/scale);
    if d>1e-5
        error('Stored no-loss MATLAB mode %d was not reproduced (distance %.3g).',k,d);
    end
end
ml=lossForNoLoss(m0);
if any(~isfinite(ml)),error('At least one selected MATLAB no-loss mode was not tracked.');end

[ok,row]=ismember(C.comsol_index,CT.no_loss_index);
if ~all(ok),error('COMSOL TVB tracking is incomplete.');end
CT=CT(row,:);
mat0=S0.frequency(m0);matL=SL.frequency(ml);
matMAC=MAC(sub2ind(size(MAC),m0,ml));
matIncrement=imag(matL)-imag(mat0);
comIncrement=CT.imag_increment_Hz;

T=table(C.comsol_index,CT.tvb_root_index,CT.MAC,m0,ml,matMAC, ...
    C.frequency_real_Hz,C.frequency_imag_Hz,CT.tvb_real_Hz,CT.tvb_imag_Hz, ...
    real(mat0),imag(mat0),real(matL),imag(matL),comIncrement,matIncrement, ...
    'VariableNames',{'solution_index','comsol_tvb_root','comsol_MAC', ...
    'matlab_no_loss_index','matlab_tvb_index','matlab_MAC', ...
    'comsol_no_loss_real_Hz','comsol_no_loss_imag_Hz', ...
    'comsol_tvb_real_Hz','comsol_tvb_imag_Hz', ...
    'matlab_no_loss_real_Hz','matlab_no_loss_imag_Hz', ...
    'matlab_tvb_real_Hz','matlab_tvb_imag_Hz', ...
    'comsol_loss_increment_Hz','matlab_loss_increment_Hz'});
T.no_loss_real_relative_error=abs(T.matlab_no_loss_real_Hz- ...
    T.comsol_no_loss_real_Hz)./abs(T.comsol_no_loss_real_Hz);
T.tvb_real_relative_error=abs(T.matlab_tvb_real_Hz-T.comsol_tvb_real_Hz)./ ...
    max(abs(T.comsol_tvb_real_Hz),eps);
T.tvb_imag_absolute_error_Hz=abs(T.matlab_tvb_imag_Hz-T.comsol_tvb_imag_Hz);
T.loss_increment_absolute_error_Hz=abs(matIncrement-comIncrement);
T.loss_increment_relative_error=T.loss_increment_absolute_error_Hz./ ...
    max(abs(comIncrement),opt.MeaningfulLossFloorHz);
T.meaningful_loss=abs(comIncrement)>=opt.MeaningfulLossFloorHz;
T.loss_within_10pct=T.loss_increment_relative_error<=0.10 & T.meaningful_loss;

if ~exist(opt.OutputDir,'dir'),mkdir(opt.OutputDir);end
writetable(T,fullfile(opt.OutputDir,'tvb_mode_by_mode_comparison.csv'));
P=table(T.solution_index,T.comsol_tvb_real_Hz,T.comsol_tvb_imag_Hz, ...
    CT.tvb_Forward,CT.tvb_Backward,T.matlab_tvb_real_Hz,T.matlab_tvb_imag_Hz, ...
    SL.table.Eoz1_fraction(ml),SL.table.Eof1_fraction(ml), ...
    T.tvb_real_relative_error, ...
    abs(T.matlab_tvb_imag_Hz-T.comsol_tvb_imag_Hz)./max(abs(T.comsol_tvb_imag_Hz),1), ...
    'VariableNames',{'solution_index','comsol_real_Hz','comsol_imag_Hz', ...
    'comsol_Forward','comsol_Backward','matlab_real_Hz','matlab_imag_Hz', ...
    'matlab_Forward','matlab_Backward','real_relative_error','imag_relative_error'});
plot_comsol_matlab_modes(P,fullfile(opt.OutputDir,'tvb_comsol_matlab'), ...
    'Title','Thermoviscous eigenmodes: COMSOL vs MATLAB', ...
    'RealTolerance',0.10,'ImagTolerance',0.10);
meaningful=T.meaningful_loss;
S=table(n,nnz(meaningful),max(T.no_loss_real_relative_error), ...
    median(T.tvb_real_relative_error),max(T.tvb_real_relative_error), ...
    median(T.loss_increment_relative_error(meaningful)), ...
    max(T.loss_increment_relative_error(meaningful)), ...
    nnz(T.loss_within_10pct), ...
    'VariableNames',{'mode_count','meaningful_loss_mode_count', ...
    'max_no_loss_real_relative_error','median_tvb_real_relative_error', ...
    'max_tvb_real_relative_error','median_loss_increment_relative_error', ...
    'max_loss_increment_relative_error','loss_modes_within_10pct'});
writetable(S,fullfile(opt.OutputDir,'tvb_comparison_summary.csv'));
fprintf('TVB comparison: %d modes; meaningful loss=%d; within 10%%=%d\n', ...
    n,nnz(meaningful),nnz(T.loss_within_10pct));
fprintf('Loss-increment relative error: median %.2f%%, max %.2f%%\n', ...
    100*S.median_loss_increment_relative_error,100*S.max_loss_increment_relative_error);
end
